//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace BL.HotelTSWebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TestService", Namespace="http://tempuri.org/")]
    public partial class SOAPHeaderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UserCredentials userCredentialsValueField;
        
        private System.Threading.SendOrPostCallback GetHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailableRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookedRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSlotOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPHeaderService() {
            this.Url = global::BL.Properties.Settings.Default.BL_HotelTSWebServices_SOAPHeaderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UserCredentials UserCredentialsValue {
            get {
                return this.userCredentialsValueField;
            }
            set {
                this.userCredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelsCompletedEventHandler GetHotelsCompleted;
        
        /// <remarks/>
        public event GetRoomCompletedEventHandler GetRoomCompleted;
        
        /// <remarks/>
        public event GetAvailableRoomsCompletedEventHandler GetAvailableRoomsCompleted;
        
        /// <remarks/>
        public event BookRoomCompletedEventHandler BookRoomCompleted;
        
        /// <remarks/>
        public event GetBookedRoomsCompletedEventHandler GetBookedRoomsCompleted;
        
        /// <remarks/>
        public event UpdateSlotCompletedEventHandler UpdateSlotCompleted;
        
        /// <remarks/>
        public event ConfirmSlotCompletedEventHandler ConfirmSlotCompleted;
        
        /// <remarks/>
        public event DeleteSlotCompletedEventHandler DeleteSlotCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHotels() {
            object[] results = this.Invoke("GetHotels", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelsAsync() {
            this.GetHotelsAsync(null);
        }
        
        /// <remarks/>
        public void GetHotelsAsync(object userState) {
            if ((this.GetHotelsOperationCompleted == null)) {
                this.GetHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelsOperationCompleted);
            }
            this.InvokeAsync("GetHotels", new object[0], this.GetHotelsOperationCompleted, userState);
        }
        
        private void OnGetHotelsOperationCompleted(object arg) {
            if ((this.GetHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelsCompleted(this, new GetHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRoom(int hotelId) {
            object[] results = this.Invoke("GetRoom", new object[] {
                        hotelId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomAsync(int hotelId) {
            this.GetRoomAsync(hotelId, null);
        }
        
        /// <remarks/>
        public void GetRoomAsync(int hotelId, object userState) {
            if ((this.GetRoomOperationCompleted == null)) {
                this.GetRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomOperationCompleted);
            }
            this.InvokeAsync("GetRoom", new object[] {
                        hotelId}, this.GetRoomOperationCompleted, userState);
        }
        
        private void OnGetRoomOperationCompleted(object arg) {
            if ((this.GetRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomCompleted(this, new GetRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAvailableRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAvailableRooms(int hotelId, int roomId, System.DateTime travelDate) {
            object[] results = this.Invoke("GetAvailableRooms", new object[] {
                        hotelId,
                        roomId,
                        travelDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailableRoomsAsync(int hotelId, int roomId, System.DateTime travelDate) {
            this.GetAvailableRoomsAsync(hotelId, roomId, travelDate, null);
        }
        
        /// <remarks/>
        public void GetAvailableRoomsAsync(int hotelId, int roomId, System.DateTime travelDate, object userState) {
            if ((this.GetAvailableRoomsOperationCompleted == null)) {
                this.GetAvailableRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableRoomsOperationCompleted);
            }
            this.InvokeAsync("GetAvailableRooms", new object[] {
                        hotelId,
                        roomId,
                        travelDate}, this.GetAvailableRoomsOperationCompleted, userState);
        }
        
        private void OnGetAvailableRoomsOperationCompleted(object arg) {
            if ((this.GetAvailableRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableRoomsCompleted(this, new GetAvailableRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BookRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BookRoom(int roomId, string roomNumber, int hotelId, System.DateTime travelDate, bool isLocked, string passengerSSN, string updatedUser) {
            object[] results = this.Invoke("BookRoom", new object[] {
                        roomId,
                        roomNumber,
                        hotelId,
                        travelDate,
                        isLocked,
                        passengerSSN,
                        updatedUser});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BookRoomAsync(int roomId, string roomNumber, int hotelId, System.DateTime travelDate, bool isLocked, string passengerSSN, string updatedUser) {
            this.BookRoomAsync(roomId, roomNumber, hotelId, travelDate, isLocked, passengerSSN, updatedUser, null);
        }
        
        /// <remarks/>
        public void BookRoomAsync(int roomId, string roomNumber, int hotelId, System.DateTime travelDate, bool isLocked, string passengerSSN, string updatedUser, object userState) {
            if ((this.BookRoomOperationCompleted == null)) {
                this.BookRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookRoomOperationCompleted);
            }
            this.InvokeAsync("BookRoom", new object[] {
                        roomId,
                        roomNumber,
                        hotelId,
                        travelDate,
                        isLocked,
                        passengerSSN,
                        updatedUser}, this.BookRoomOperationCompleted, userState);
        }
        
        private void OnBookRoomOperationCompleted(object arg) {
            if ((this.BookRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookRoomCompleted(this, new BookRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookedRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetBookedRooms(int roomId, System.DateTime travelDate) {
            object[] results = this.Invoke("GetBookedRooms", new object[] {
                        roomId,
                        travelDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookedRoomsAsync(int roomId, System.DateTime travelDate) {
            this.GetBookedRoomsAsync(roomId, travelDate, null);
        }
        
        /// <remarks/>
        public void GetBookedRoomsAsync(int roomId, System.DateTime travelDate, object userState) {
            if ((this.GetBookedRoomsOperationCompleted == null)) {
                this.GetBookedRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookedRoomsOperationCompleted);
            }
            this.InvokeAsync("GetBookedRooms", new object[] {
                        roomId,
                        travelDate}, this.GetBookedRoomsOperationCompleted, userState);
        }
        
        private void OnGetBookedRoomsOperationCompleted(object arg) {
            if ((this.GetBookedRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookedRoomsCompleted(this, new GetBookedRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateSlot(int bookId, int roomId, int hotelId, System.DateTime travelDate) {
            object[] results = this.Invoke("UpdateSlot", new object[] {
                        bookId,
                        roomId,
                        hotelId,
                        travelDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSlotAsync(int bookId, int roomId, int hotelId, System.DateTime travelDate) {
            this.UpdateSlotAsync(bookId, roomId, hotelId, travelDate, null);
        }
        
        /// <remarks/>
        public void UpdateSlotAsync(int bookId, int roomId, int hotelId, System.DateTime travelDate, object userState) {
            if ((this.UpdateSlotOperationCompleted == null)) {
                this.UpdateSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSlotOperationCompleted);
            }
            this.InvokeAsync("UpdateSlot", new object[] {
                        bookId,
                        roomId,
                        hotelId,
                        travelDate}, this.UpdateSlotOperationCompleted, userState);
        }
        
        private void OnUpdateSlotOperationCompleted(object arg) {
            if ((this.UpdateSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSlotCompleted(this, new UpdateSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmSlot(int bId, string userName, decimal paidAmount) {
            object[] results = this.Invoke("ConfirmSlot", new object[] {
                        bId,
                        userName,
                        paidAmount});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmSlotAsync(int bId, string userName, decimal paidAmount) {
            this.ConfirmSlotAsync(bId, userName, paidAmount, null);
        }
        
        /// <remarks/>
        public void ConfirmSlotAsync(int bId, string userName, decimal paidAmount, object userState) {
            if ((this.ConfirmSlotOperationCompleted == null)) {
                this.ConfirmSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmSlotOperationCompleted);
            }
            this.InvokeAsync("ConfirmSlot", new object[] {
                        bId,
                        userName,
                        paidAmount}, this.ConfirmSlotOperationCompleted, userState);
        }
        
        private void OnConfirmSlotOperationCompleted(object arg) {
            if ((this.ConfirmSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmSlotCompleted(this, new ConfirmSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteSlot(int bookId) {
            object[] results = this.Invoke("DeleteSlot", new object[] {
                        bookId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSlotAsync(int bookId) {
            this.DeleteSlotAsync(bookId, null);
        }
        
        /// <remarks/>
        public void DeleteSlotAsync(int bookId, object userState) {
            if ((this.DeleteSlotOperationCompleted == null)) {
                this.DeleteSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSlotOperationCompleted);
            }
            this.InvokeAsync("DeleteSlot", new object[] {
                        bookId}, this.DeleteSlotOperationCompleted, userState);
        }
        
        private void OnDeleteSlotOperationCompleted(object arg) {
            if ((this.DeleteSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSlotCompleted(this, new DeleteSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class UserCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetHotelsCompletedEventHandler(object sender, GetHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRoomCompletedEventHandler(object sender, GetRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAvailableRoomsCompletedEventHandler(object sender, GetAvailableRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BookRoomCompletedEventHandler(object sender, BookRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetBookedRoomsCompletedEventHandler(object sender, GetBookedRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookedRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookedRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateSlotCompletedEventHandler(object sender, UpdateSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConfirmSlotCompletedEventHandler(object sender, ConfirmSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteSlotCompletedEventHandler(object sender, DeleteSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591