//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace BL.AirwayTSWebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TestService", Namespace="http://tempuri.org/")]
    public partial class SOAPHeaderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UserCredentials userCredentialsValueField;
        
        private System.Threading.SendOrPostCallback GetAirlinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAirbusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSlotsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookedSlotsOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookSlotOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSlotsTestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPHeaderService() {
            this.Url = global::BL.Properties.Settings.Default.BL_AirwayTSWebServices_SOAPHeaderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UserCredentials UserCredentialsValue {
            get {
                return this.userCredentialsValueField;
            }
            set {
                this.userCredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAirlinesCompletedEventHandler GetAirlinesCompleted;
        
        /// <remarks/>
        public event GetAirbusCompletedEventHandler GetAirbusCompleted;
        
        /// <remarks/>
        public event UpdateSlotCompletedEventHandler UpdateSlotCompleted;
        
        /// <remarks/>
        public event ConfirmSlotCompletedEventHandler ConfirmSlotCompleted;
        
        /// <remarks/>
        public event DeleteSlotCompletedEventHandler DeleteSlotCompleted;
        
        /// <remarks/>
        public event GetSlotsCompletedEventHandler GetSlotsCompleted;
        
        /// <remarks/>
        public event GetBookedSlotsCompletedEventHandler GetBookedSlotsCompleted;
        
        /// <remarks/>
        public event BookSlotCompletedEventHandler BookSlotCompleted;
        
        /// <remarks/>
        public event GetSlotsTestCompletedEventHandler GetSlotsTestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAirlines", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAirlines() {
            object[] results = this.Invoke("GetAirlines", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAirlinesAsync() {
            this.GetAirlinesAsync(null);
        }
        
        /// <remarks/>
        public void GetAirlinesAsync(object userState) {
            if ((this.GetAirlinesOperationCompleted == null)) {
                this.GetAirlinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirlinesOperationCompleted);
            }
            this.InvokeAsync("GetAirlines", new object[0], this.GetAirlinesOperationCompleted, userState);
        }
        
        private void OnGetAirlinesOperationCompleted(object arg) {
            if ((this.GetAirlinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirlinesCompleted(this, new GetAirlinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAirbus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAirbus(int airlineId, string from, string to) {
            object[] results = this.Invoke("GetAirbus", new object[] {
                        airlineId,
                        from,
                        to});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAirbusAsync(int airlineId, string from, string to) {
            this.GetAirbusAsync(airlineId, from, to, null);
        }
        
        /// <remarks/>
        public void GetAirbusAsync(int airlineId, string from, string to, object userState) {
            if ((this.GetAirbusOperationCompleted == null)) {
                this.GetAirbusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirbusOperationCompleted);
            }
            this.InvokeAsync("GetAirbus", new object[] {
                        airlineId,
                        from,
                        to}, this.GetAirbusOperationCompleted, userState);
        }
        
        private void OnGetAirbusOperationCompleted(object arg) {
            if ((this.GetAirbusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirbusCompleted(this, new GetAirbusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateSlot(int bookId, int airbusId, int slotNumber, System.DateTime travelDate) {
            object[] results = this.Invoke("UpdateSlot", new object[] {
                        bookId,
                        airbusId,
                        slotNumber,
                        travelDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSlotAsync(int bookId, int airbusId, int slotNumber, System.DateTime travelDate) {
            this.UpdateSlotAsync(bookId, airbusId, slotNumber, travelDate, null);
        }
        
        /// <remarks/>
        public void UpdateSlotAsync(int bookId, int airbusId, int slotNumber, System.DateTime travelDate, object userState) {
            if ((this.UpdateSlotOperationCompleted == null)) {
                this.UpdateSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSlotOperationCompleted);
            }
            this.InvokeAsync("UpdateSlot", new object[] {
                        bookId,
                        airbusId,
                        slotNumber,
                        travelDate}, this.UpdateSlotOperationCompleted, userState);
        }
        
        private void OnUpdateSlotOperationCompleted(object arg) {
            if ((this.UpdateSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSlotCompleted(this, new UpdateSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmSlot(int bId, string userName, decimal paidAmount) {
            object[] results = this.Invoke("ConfirmSlot", new object[] {
                        bId,
                        userName,
                        paidAmount});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmSlotAsync(int bId, string userName, decimal paidAmount) {
            this.ConfirmSlotAsync(bId, userName, paidAmount, null);
        }
        
        /// <remarks/>
        public void ConfirmSlotAsync(int bId, string userName, decimal paidAmount, object userState) {
            if ((this.ConfirmSlotOperationCompleted == null)) {
                this.ConfirmSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmSlotOperationCompleted);
            }
            this.InvokeAsync("ConfirmSlot", new object[] {
                        bId,
                        userName,
                        paidAmount}, this.ConfirmSlotOperationCompleted, userState);
        }
        
        private void OnConfirmSlotOperationCompleted(object arg) {
            if ((this.ConfirmSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmSlotCompleted(this, new ConfirmSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteSlot(int bookId) {
            object[] results = this.Invoke("DeleteSlot", new object[] {
                        bookId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSlotAsync(int bookId) {
            this.DeleteSlotAsync(bookId, null);
        }
        
        /// <remarks/>
        public void DeleteSlotAsync(int bookId, object userState) {
            if ((this.DeleteSlotOperationCompleted == null)) {
                this.DeleteSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSlotOperationCompleted);
            }
            this.InvokeAsync("DeleteSlot", new object[] {
                        bookId}, this.DeleteSlotOperationCompleted, userState);
        }
        
        private void OnDeleteSlotOperationCompleted(object arg) {
            if ((this.DeleteSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSlotCompleted(this, new DeleteSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSlots", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSlots(int airbusId, System.DateTime travelDate) {
            object[] results = this.Invoke("GetSlots", new object[] {
                        airbusId,
                        travelDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSlotsAsync(int airbusId, System.DateTime travelDate) {
            this.GetSlotsAsync(airbusId, travelDate, null);
        }
        
        /// <remarks/>
        public void GetSlotsAsync(int airbusId, System.DateTime travelDate, object userState) {
            if ((this.GetSlotsOperationCompleted == null)) {
                this.GetSlotsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSlotsOperationCompleted);
            }
            this.InvokeAsync("GetSlots", new object[] {
                        airbusId,
                        travelDate}, this.GetSlotsOperationCompleted, userState);
        }
        
        private void OnGetSlotsOperationCompleted(object arg) {
            if ((this.GetSlotsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSlotsCompleted(this, new GetSlotsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBookedSlots", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetBookedSlots(int airbusId) {
            object[] results = this.Invoke("GetBookedSlots", new object[] {
                        airbusId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookedSlotsAsync(int airbusId) {
            this.GetBookedSlotsAsync(airbusId, null);
        }
        
        /// <remarks/>
        public void GetBookedSlotsAsync(int airbusId, object userState) {
            if ((this.GetBookedSlotsOperationCompleted == null)) {
                this.GetBookedSlotsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookedSlotsOperationCompleted);
            }
            this.InvokeAsync("GetBookedSlots", new object[] {
                        airbusId}, this.GetBookedSlotsOperationCompleted, userState);
        }
        
        private void OnGetBookedSlotsOperationCompleted(object arg) {
            if ((this.GetBookedSlotsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookedSlotsCompleted(this, new GetBookedSlotsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BookSlot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BookSlot(int airbusId, int seatNumber, System.DateTime travelDate, bool isLocked, string passengerSSN, string updatedUser) {
            object[] results = this.Invoke("BookSlot", new object[] {
                        airbusId,
                        seatNumber,
                        travelDate,
                        isLocked,
                        passengerSSN,
                        updatedUser});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BookSlotAsync(int airbusId, int seatNumber, System.DateTime travelDate, bool isLocked, string passengerSSN, string updatedUser) {
            this.BookSlotAsync(airbusId, seatNumber, travelDate, isLocked, passengerSSN, updatedUser, null);
        }
        
        /// <remarks/>
        public void BookSlotAsync(int airbusId, int seatNumber, System.DateTime travelDate, bool isLocked, string passengerSSN, string updatedUser, object userState) {
            if ((this.BookSlotOperationCompleted == null)) {
                this.BookSlotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookSlotOperationCompleted);
            }
            this.InvokeAsync("BookSlot", new object[] {
                        airbusId,
                        seatNumber,
                        travelDate,
                        isLocked,
                        passengerSSN,
                        updatedUser}, this.BookSlotOperationCompleted, userState);
        }
        
        private void OnBookSlotOperationCompleted(object arg) {
            if ((this.BookSlotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookSlotCompleted(this, new BookSlotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSlotsTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSlotsTest(int airbusId, System.DateTime travelDate) {
            object[] results = this.Invoke("GetSlotsTest", new object[] {
                        airbusId,
                        travelDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSlotsTestAsync(int airbusId, System.DateTime travelDate) {
            this.GetSlotsTestAsync(airbusId, travelDate, null);
        }
        
        /// <remarks/>
        public void GetSlotsTestAsync(int airbusId, System.DateTime travelDate, object userState) {
            if ((this.GetSlotsTestOperationCompleted == null)) {
                this.GetSlotsTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSlotsTestOperationCompleted);
            }
            this.InvokeAsync("GetSlotsTest", new object[] {
                        airbusId,
                        travelDate}, this.GetSlotsTestOperationCompleted, userState);
        }
        
        private void OnGetSlotsTestOperationCompleted(object arg) {
            if ((this.GetSlotsTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSlotsTestCompleted(this, new GetSlotsTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class UserCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAirlinesCompletedEventHandler(object sender, GetAirlinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirlinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirlinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAirbusCompletedEventHandler(object sender, GetAirbusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirbusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirbusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateSlotCompletedEventHandler(object sender, UpdateSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConfirmSlotCompletedEventHandler(object sender, ConfirmSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteSlotCompletedEventHandler(object sender, DeleteSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSlotsCompletedEventHandler(object sender, GetSlotsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSlotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSlotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetBookedSlotsCompletedEventHandler(object sender, GetBookedSlotsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookedSlotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookedSlotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BookSlotCompletedEventHandler(object sender, BookSlotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookSlotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookSlotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSlotsTestCompletedEventHandler(object sender, GetSlotsTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSlotsTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSlotsTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591